### ISSUE TITLE
CRASH cleanup of drfuzz_test_empty

### ISSUE THREAD

**Issue by derekbruening** [DynamoRIO/drmemory#1745]
On my Fedora 20 machine drfuzz_test_empty fails every time in every build:

```
drheapstat-dbg-32: 30 tests passed, **** 1 tests failed: ****
        drfuzz_test_empty 
drheapstat-rel-32: 30 tests passed, **** 1 tests failed: ****
        drfuzz_test_empty 
drmemory-dbg-32: 67 tests passed, **** 1 tests failed: ****
        drfuzz_test_empty 
drmemory-dbg-64: 14 tests passed, **** 1 tests failed: ****
        drfuzz_test_empty 
drmemory-rel-32: 67 tests passed, **** 1 tests failed: ****
        drfuzz_test_empty 
drmemory-rel-64: 14 tests passed, **** 1 tests failed: ****
        drfuzz_test_empty 
final package: build successful; no tests for this build
```

The suite log files show that it crashes:

```
<Stopping application /work/drmemory/build_suite/build_drmemory-dbg-32/tests/drfuzz_test_empty (4343)>
<Application /work/drmemory/build_suite/build_drmemory-dbg-32/tests/drfuzz_test_empty (4343).  Tool internal crash at PC 0x790074e8.  Please report this at your tool's issue tracker.  Program aborted.
Received SIGSEGV at pc 0x790074e8 in thread 4343
Base: 0xf7000000
Registers:eax=0x00000000 ebx=0x79016000 ecx=0x5296a95c edx=0x00000140
        esi=0x000010f7 edi=0xf739e000 esp=0x5296a900 ebp=0x5296a910
        eflags=0x00010202
version 5.0.16625, custom build
-no_dynamic_options -client_lib '/work/drmemory/build_suite/build_drmemory-dbg-32/tests/libdrfuzz_test_empty.client.so;0;' -code_api -stack_size 56K -max_elide_jmp 0 -max_elide_call 0 -early_inject -emulate_brk -no_inline_ignored_syscalls -native_exec_default_list '' -no_native_exec_managed_code -no_indcall2direct 
0x5296a910 0x79007654
0x5296a930 0x7900d4b0
0x5296aaa4 0xf71e298c
0x5296aae0 0xf7074ca5
0x5296aaf0 0xf707323a
0x5296ab10 0xf70733fc
0x5296ab40 0xf7278913
0x5296ab50 0x529113c0
0xf729a501 0x5e5b0000>
```

Attaching gdb to a manual run:

```
(gdb) bt
#0  0x790074e8 in drwrap_free_user_data (drcontext=0x4da593c0, pt=0x0, i=0)
    at /work/drmemory/git/src/dynamorio/ext/drwrap/drwrap.c:965
#1  0x79007654 in drwrap_thread_exit (drcontext=0x4da593c0)
    at /work/drmemory/git/src/dynamorio/ext/drwrap/drwrap.c:988
#2  0x7900d4b0 in drmgr_thread_exit_event (drcontext=0x4da593c0)
    at /work/drmemory/git/src/dynamorio/ext/drmgr/drmgr.c:1671
#3  0xf71e298c in instrument_thread_exit_event (dcontext=0x4da593c0)
    at /work/drmemory/git/src/dynamorio/core/lib/instrument.c:1242
#4  0xf7074ca5 in dynamo_thread_exit_pre_client (dcontext=0x4da593c0, id=22401)
    at /work/drmemory/git/src/dynamorio/core/dynamo.c:2271
#5  0xf707323a in dynamo_process_exit_cleanup () at /work/drmemory/git/src/dynamorio/core/dynamo.c:1220
#6  0xf70733fc in dynamo_process_exit () at /work/drmemory/git/src/dynamorio/core/dynamo.c:1294
```

**Comment by derekbruening** [comment]
The bug is that there are 2 copies of drmgr and they clobber each other's DR TLS field:

```
Breakpoint 1, dr_set_tls_field (drcontext=0xef0213c0, value=0xef07ed14) at /work/drmemory/git/src/dynamorio/core/lib/instrument.c:4415
4415        dcontext_t *dcontext = (dcontext_t *) drcontext;
(gdb) bt
#0  dr_set_tls_field (drcontext=0xef0213c0, value=0xef07ed14) at /work/drmemory/git/src/dynamorio/core/lib/instrument.c:4415
#1  0x7900d3a7 in drmgr_thread_init_event (drcontext=0xef0213c0) at /work/drmemory/git/src/dynamorio/ext/drmgr/drmgr.c:1640
#2  0xf71e266f in instrument_thread_init (dcontext=0xef0213c0, client_thread=false, valid_mc=false)
    at /work/drmemory/git/src/dynamorio/core/lib/instrument.c:1198
#3  0xf71e1311 in instrument_init () at /work/drmemory/git/src/dynamorio/core/lib/instrument.c:604
#4  0xf70723ea in dynamorio_app_init () at /work/drmemory/git/src/dynamorio/core/dynamo.c:645
#5  0xf72bbe1d in privload_early_inject (sp=0xffb11bb0, old_libdr_base=0x0, old_libdr_size=0)
    at /work/drmemory/git/src/dynamorio/core/unix/loader.c:1807
#6  0xf72789cf in _start () at /work/drmemory/git/src/dynamorio/core/arch/x86/x86.asm:1177
(gdb) c
Continuing.

Breakpoint 1, dr_set_tls_field (drcontext=0xef0213c0, value=0xef07f768) at /work/drmemory/git/src/dynamorio/core/lib/instrument.c:4415
4415        dcontext_t *dcontext = (dcontext_t *) drcontext;
(gdb) bt
#0  dr_set_tls_field (drcontext=0xef0213c0, value=0xef07f768) at /work/drmemory/git/src/dynamorio/core/lib/instrument.c:4415
#1  0xf76f1fd7 in drmgr_thread_init_event (drcontext=0xef0213c0) at /work/drmemory/git/src/dynamorio/ext/drmgr/drmgr.c:1640
#2  0xf71e266f in instrument_thread_init (dcontext=0xef0213c0, client_thread=false, valid_mc=false)
    at /work/drmemory/git/src/dynamorio/core/lib/instrument.c:1198
#3  0xf71e1311 in instrument_init () at /work/drmemory/git/src/dynamorio/core/lib/instrument.c:604
#4  0xf70723ea in dynamorio_app_init () at /work/drmemory/git/src/dynamorio/core/dynamo.c:645
#5  0xf72bbe1d in privload_early_inject (sp=0xffb11bb0, old_libdr_base=0x0, old_libdr_size=0)
    at /work/drmemory/git/src/dynamorio/core/unix/loader.c:1807
#6  0xf72789cf in _start () at /work/drmemory/git/src/dynamorio/core/arch/x86/x86.asm:1177
```

It seems like it should crash for everyone.  It may depend on the value of uninitialized heap used in drmgr's TLS arrays.
