### ISSUE TITLE
leak scan at process exit is really slow on ARM

### ISSUE THREAD

**Issue by derekbruening** [DynamoRIO/drmemory#1852]
Split from #1726

Running "base_unittests --single-process-tests --gtest_filter=FileTest.MemoryCorruption", the leak scan time really shows up as this test forks 9 separate child processes.

gdb snapshot:

```
(gdb) bt
#0  drsym_obj_addrsearch_symtab (mod_in=0x49d6da30, modoffs=7820238, idx=0x48dea0f8)
    at /home/derek/drmemory/git/src/dynamorio/ext/drsyms/drsyms_elf.c:400
#1  0x73942fba in addrsearch_symtab (mod=0x49d6da00, modoffs=7820238, info=0x48dea3b0, flags=1)
    at /home/derek/drmemory/git/src/dynamorio/ext/drsyms/drsyms_unix_common.c:403
#2  0x7394328a in drsym_unix_lookup_address (mod_in=0x49d6da00, modoffs=7820238, out=0x48dea3b0, flags=1)
    at /home/derek/drmemory/git/src/dynamorio/ext/drsyms/drsyms_unix_common.c:560
#3  0x73942142 in drsym_lookup_address_local (modpath=0x48e2b324 "/mnt/usbkey/chrome-arm-build/Release/base_unittests", 
    modoffs=7820238, out=0x48dea3b0, flags=1) at /home/derek/drmemory/git/src/dynamorio/ext/drsyms/drsyms_unix_frontend.c:153
#4  0x73942316 in drsym_lookup_address (modpath=0x48e2b324 "/mnt/usbkey/chrome-arm-build/Release/base_unittests", modoffs=7820238, 
    out=0x48dea3b0, flags=1) at /home/derek/drmemory/git/src/dynamorio/ext/drsyms/drsyms_unix_frontend.c:245
#5  0x738b2670 in lookup_func_and_line (frame=0x48e75f28, name_info=0x48e2b2f4, modoffs=7820238)
    at /home/derek/drmemory/git/src/common/callstack.c:541
#6  0x738c5384 in packed_frame_to_symbolized (pcs=0x493f84e0, frame=0x48e75f28, idx=6)
    at /home/derek/drmemory/git/src/common/callstack.c:2115
#7  0x738c5f66 in packed_callstack_to_symbolized (pcs=0x493f84e0, scs=0x48dea4f8)
    at /home/derek/drmemory/git/src/common/callstack.c:2160
#8  0x739002d8 in report_leak (known_malloc=1 '\001', addr=0x8c18f0 "\016", size=27, indirect_size=0, early=0 '\000', 
    reachable=1 '\001', maybe_reachable=0 '\000', shadow_state=5, pcs=0x493f84e0, count_reachable=1 '\001', show_reachable=0 '\000')
    at /home/derek/drmemory/git/src/drmemory/report.c:3448
#9  0x738d78f0 in client_found_leak (start=0x8c18f0 "\016", 
    end=0x8c190b "\361\375\361\375\361\375\361\375\361\375\361\375\361\375\361\375\361\375\361\375\361X\205?I\030", 
    indirect_bytes=0, pre_us=0 '\000', reachable=1 '\001', maybe_reachable=0 '\000', client_data=0x493f84e0, 
    count_reachable=1 '\001', show_reachable=0 '\000') at /home/derek/drmemory/git/src/drmemory/alloc_drmem.c:2548
#10 0x7390da68 in malloc_iterate_cb (info=0x48dea71c, iter_data=0x48dea90c) at /home/derek/drmemory/git/src/drmemory/leak.c:1249
#11 0x738a0c48 in alloc_iter_own_arena (iter_arena_start=0x8ac000 "", iter_arena_end=0x9c3000 <Address 0x9c3000 out of bounds>, 
    flags=2, iter_data=0x48dea87c) at /home/derek/drmemory/git/src/common/alloc_replace.c:2336
#12 0x738b0d54 in rb_iter_cb (node=0x48e185ec, data=0x48dea830) at /home/derek/drmemory/git/src/common/heap.c:1024
#13 0x73918c18 in iterate_helper (tree=0x48e18d94, node=0x48e185ec, iter_cb=0x738b0add <rb_iter_cb>, iter_data=0x48dea830)
    at /home/derek/drmemory/git/src/common/redblack.c:670
#14 0x73918f26 in rb_iterate (tree=0x48e18d94, iter_cb=0x738b0add <rb_iter_cb>, iter_data=0x48dea830)
    at /home/derek/drmemory/git/src/common/redblack.c:684
#15 0x738b0dee in heap_region_iterate (iter_cb=0x738a050d <alloc_iter_own_arena>, data=0x48dea87c)
    at /home/derek/drmemory/git/src/common/heap.c:1037
#16 0x738a1246 in alloc_iterate (cb=0x7390d075 <malloc_iterate_cb>, iter_data=0x48dea90c, only_live=1 '\001')
    at /home/derek/drmemory/git/src/common/alloc_replace.c:2370
#17 0x738a92aa in malloc_replace__iterate (cb=0x7390d075 <malloc_iterate_cb>, iter_data=0x48dea90c)
    at /home/derek/drmemory/git/src/common/alloc_replace.c:5189
#18 0x738844b6 in malloc_iterate (cb=0x7390d075 <malloc_iterate_cb>, iter_data=0x48dea90c)
    at /home/derek/drmemory/git/src/common/alloc.c:3785
#19 0x7390f7a6 in leak_scan_for_leaks (at_exit=1 '\001') at /home/derek/drmemory/git/src/drmemory/leak.c:1482
#20 0x738d7a40 in check_reachability (at_exit=1 '\001') at /home/derek/drmemory/git/src/drmemory/alloc_drmem.c:2584
#21 0x738133c0 in event_exit () at /home/derek/drmemory/git/src/drmemory/drmemory.c:400
#22 0x711c2404 in instrument_exit () at /home/derek/drmemory/git/src/dynamorio/core/lib/instrument.c:765
```

Should we turn off reporting of reachable leaks?
By default we count and de-dup them, and we support suppressions:

```
~~Dr.M~~ ERRORS IGNORED:
~~Dr.M~~      50 unique,    81 total,   9869 byte(s) of still-reachable allocation(s)
```

Although we only need to symbolize to check suppressions, right?  Not to
de-dup.  We could drop the feature of suppressing reachable when !show_reachable?

Perf tests running:
```
# /usr/bin/time bin/drmemory -pause_at_assert -dr_ops "-msgbox_mask 12 -checklevel 0" -- /mnt/usbkey/chrome-arm-build/Release/base_unittests --single-process-tests --gtest_filter=FileTest.MemoryCorruption
```

defaults:
1041.97user 17.25system 17:43.28elapsed 99%CPU (0avgtext+0avgdata 568224maxresident)k

-no_count_leaks:
83.70user 0.82system 1:24.94elapsed 99%CPU (0avgtext+0avgdata 171888maxresident)k

-no_leak_scan:
87.30user 0.88system 1:28.59elapsed 99%CPU (0avgtext+0avgdata 171920maxresident)k

defaults but w/ the proposed scheme of avoiding symbolization (and thus
suppression) of reachable leaks:
113.33user 15.14system 2:09.57elapsed 99%CPU (0avgtext+0avgdata 261312maxresident)k

exit report_leak right up front for reachable:
110.77user 14.67system 2:06.02elapsed 99%CPU (0avgtext+0avgdata 261280maxresident)k

avoid symbolization for all leaks:
86.88user 0.89system 1:28.17elapsed 99%CPU (0avgtext+0avgdata 171920maxresident)k

So symbolization is where the vast majority of the cost is.  There must be
something specific to ARM?
Xref #1770: maybe there's some other low-hanging drsyms fruit.

**Comment by derekbruening** [comment]
This particular test does not exist anymore (my ARM build is old).  It might be nice to do further tests but maybe the reachable symbolization by itself is enough and the 1:28 to 2:09 is acceptable for 9 children
exiting (40s/9 = <5s each).    We'll reopen if that's the case or open a new issue, and we'll leave this one as covering the reachable no-symbolize proposal.
